### ISSUE TITLE
Bias Tee support

### ISSUE THREAD

**Issue by Cherenkov11** [rsadsb/dump1090_rs#16]
Hello, I'm using regular RTL-SDR V3 with a general-use LNA. But I'm not able to enable the bias-t when using dump1090_rs.

Is it supported?

**Comment by wcampbell0x2a** [comment]
Welcome!

I added a MR that should fix your issue. I had to contribute to the soapysdr-rs bindings since they didn't support this. 

You will be able to run as `cargo r -- --driver rtlsdr --custom-config config.toml`.

with `config.toml`:
```
[[sdr]]
driver = "rtlsdr"

[[sdrs.setting]]
key = "biastee"
value = "true"

[[sdr.gain]]
key = "GAIN"
value = 20.0
```

I can confirm that soapysdr says that the setting changed, it would be awesome if you could test that with your setup. I have nothing that uses bias-t power.

**Comment by Cherenkov11** [comment]
Ok, I cloned the `add-sdr-config-settings` branch and tried to compiled but your `config.toml` was incorrect, I had to modified like this:

```
[[sdrs]]
driver = "rtlsdr"

[[sdrs.setting]]
key = "biastee"
value = "true"

[[sdrs.gain]]
key = "GAIN"
value = 15.0
```

And now `bias-t` power works as expected.

![PXL_20220223_043153249 MP](https://user-images.githubusercontent.com/29878131/155262247-466dbb5e-898c-43bc-808c-21bfbd2c2499.jpg)

Thanks

**Comment by wcampbell0x2a** [comment]
Sorry, I meant you'll have to add your own `custom_config.toml` file. I probably won't include a compiled rtlsdr config with bias-t enabled.

Glad it worked!
